[package]
name = "synchrotron-health"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
synchrotron-types = { workspace = true }
synchrotron-plugins = { workspace = true }
synchrotron-core = { workspace = true }
synchrotron-reconcile = { path = "../synchrotron-reconcile" }
serde_yaml_ng = "0.10"
tokio = { workspace = true }
tracing = { workspace = true }
