//! Sidecar plugin runtime: gRPC client speaking the protocol
//! defined in `proto/plugin.proto`.
//!
//! Unlike local plugins (subprocess per host process), sidecars are
//! long-lived containers reached over the network. The host opens a
//! gRPC channel on first use and keeps it — tonic handles HTTP/2
//! multiplexing and will reconnect on transient failures.
//!
//! Lifecycle:
//! 1. [`Sidecar::connect`] dials the endpoint with exponential
//!    backoff up to `retry.max_attempts`, then issues a `Version`
//!    RPC. A protocol-version mismatch fails registration — we do
//!    not try to speak an older protocol to a newer sidecar.
//! 2. [`Sidecar::healthcheck`] is cheap and callable any time.
//!    Sidecars that need warm-up (chart pull, cache warm) can
//!    return `ready=false` without rejecting the connection.
//! 3. [`Sidecar::render`] is the workhorse RPC. Idempotent — the
//!    caller may retry on transport failure.
//!
//! The gRPC service definition is generated by `build.rs` into the
//! [`proto`] submodule below.

use std::path::Path;
use std::time::Duration;

use thiserror::Error;
use tokio::time::sleep;
use tonic::transport::{Channel, Endpoint};
use tracing::{debug, info, warn};

pub mod proto {
    tonic::include_proto!("synchrotron.plugin.v1");
}

use proto::plugin_client::PluginClient;
use proto::{HealthcheckRequest, RenderRequest, VersionRequest};

/// Protocol version this host speaks. Must match the sidecar's
/// reply in `Version`; otherwise registration fails.
pub const PROTOCOL_VERSION: u32 = 1;

/// How aggressively to retry the initial connect. Sidecars may take
/// several seconds to become ready after their container starts.
#[derive(Debug, Clone)]
pub struct RetryConfig {
    pub max_attempts: u32,
    pub initial_backoff: Duration,
    pub max_backoff: Duration,
}

impl Default for RetryConfig {
    fn default() -> Self {
        Self {
            max_attempts: 5,
            initial_backoff: Duration::from_millis(100),
            max_backoff: Duration::from_secs(2),
        }
    }
}

#[derive(Debug, Error)]
pub enum SidecarError {
    #[error("sidecar {name}: invalid endpoint `{endpoint}`: {source}")]
    InvalidEndpoint {
        name: String,
        endpoint: String,
        #[source]
        source: tonic::transport::Error,
    },
    #[error("sidecar {name}: failed to connect after {attempts} attempts: {source}")]
    Connect {
        name: String,
        attempts: u32,
        #[source]
        source: tonic::transport::Error,
    },
    #[error("sidecar {name}: rpc `{rpc}` failed: {status}")]
    Rpc {
        name: String,
        rpc: &'static str,
        status: tonic::Status,
    },
    #[error(
        "sidecar {name}: protocol version mismatch (host speaks {host}, plugin speaks {plugin})"
    )]
    ProtocolVersion {
        name: String,
        host: u32,
        plugin: u32,
    },
    #[error("sidecar {name}: not ready: {message}")]
    NotReady { name: String, message: String },
}

#[derive(Debug, Clone)]
pub struct VersionInfo {
    pub plugin_version: String,
    pub protocol_version: u32,
}

/// Connected sidecar client. Cheap to clone — the underlying tonic
/// channel is reference-counted and multiplexes concurrent RPCs.
#[derive(Clone)]
pub struct Sidecar {
    name: String,
    client: PluginClient<Channel>,
}

impl Sidecar {
    /// Connect to `endpoint` with exponential backoff, then perform
    /// the `Version` handshake. Returns a ready-to-use client.
    pub async fn connect(
        name: impl Into<String>,
        endpoint: impl Into<String>,
        retry: &RetryConfig,
    ) -> Result<Self, SidecarError> {
        let name = name.into();
        let endpoint_str = endpoint.into();
        let endpoint = Endpoint::from_shared(endpoint_str.clone()).map_err(|source| {
            SidecarError::InvalidEndpoint {
                name: name.clone(),
                endpoint: endpoint_str.clone(),
                source,
            }
        })?;

        let mut delay = retry.initial_backoff;
        let mut last_err = None;
        for attempt in 1..=retry.max_attempts {
            match endpoint.connect().await {
                Ok(channel) => {
                    info!(
                        plugin = %name,
                        endpoint = %endpoint_str,
                        attempt,
                        "sidecar connected"
                    );
                    let mut this = Self {
                        name: name.clone(),
                        client: PluginClient::new(channel),
                    };
                    this.handshake().await?;
                    return Ok(this);
                }
                Err(e) => {
                    warn!(
                        plugin = %name,
                        endpoint = %endpoint_str,
                        attempt,
                        error = %e,
                        "sidecar connect failed; will retry"
                    );
                    last_err = Some(e);
                    if attempt < retry.max_attempts {
                        sleep(delay).await;
                        delay = (delay * 2).min(retry.max_backoff);
                    }
                }
            }
        }
        Err(SidecarError::Connect {
            name,
            attempts: retry.max_attempts,
            source: last_err.expect("at least one attempt was made"),
        })
    }

    async fn handshake(&mut self) -> Result<VersionInfo, SidecarError> {
        let resp = self
            .client
            .version(VersionRequest {
                protocol_version: PROTOCOL_VERSION,
            })
            .await
            .map_err(|status| SidecarError::Rpc {
                name: self.name.clone(),
                rpc: "Version",
                status,
            })?
            .into_inner();
        if resp.protocol_version != PROTOCOL_VERSION {
            return Err(SidecarError::ProtocolVersion {
                name: self.name.clone(),
                host: PROTOCOL_VERSION,
                plugin: resp.protocol_version,
            });
        }
        debug!(
            plugin = %self.name,
            plugin_version = %resp.plugin_version,
            "sidecar handshake ok"
        );
        Ok(VersionInfo {
            plugin_version: resp.plugin_version,
            protocol_version: resp.protocol_version,
        })
    }

    pub async fn healthcheck(&mut self) -> Result<(), SidecarError> {
        let resp = self
            .client
            .healthcheck(HealthcheckRequest {})
            .await
            .map_err(|status| SidecarError::Rpc {
                name: self.name.clone(),
                rpc: "Healthcheck",
                status,
            })?
            .into_inner();
        if !resp.ready {
            return Err(SidecarError::NotReady {
                name: self.name.clone(),
                message: resp.message,
            });
        }
        Ok(())
    }

    /// Render manifests. Returns the raw YAML/JSON document strings
    /// exactly as the plugin emitted them — the caller parses them
    /// into [`crate::Manifest`]s via `manifest::parse_stream`.
    pub async fn render(
        &mut self,
        source_path: &Path,
        params: &serde_json::Value,
    ) -> Result<Vec<String>, SidecarError> {
        let resp = self
            .client
            .render(RenderRequest {
                source_path: source_path.display().to_string(),
                params_json: params.to_string(),
            })
            .await
            .map_err(|status| SidecarError::Rpc {
                name: self.name.clone(),
                rpc: "Render",
                status,
            })?
            .into_inner();
        Ok(resp.manifests)
    }

    pub fn name(&self) -> &str {
        &self.name
    }
}

impl std::fmt::Debug for Sidecar {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("Sidecar").field("name", &self.name).finish()
    }
}
