[package]
name = "synchrotron-kube"
version.workspace = true
edition.workspace = true

[dependencies]
synchrotron-types.workspace = true
synchrotron-diff.workspace = true
synchrotron-plugins.workspace = true
serde.workspace = true
serde_yaml_ng = "0.10"
thiserror.workspace = true
tracing.workspace = true
tokio.workspace = true
serde_json.workspace = true
chrono.workspace = true
kube = { version = "0.95", default-features = false, features = ["client", "rustls-tls", "runtime"] }
k8s-openapi = { version = "0.23", default-features = false, features = ["latest"] }
futures = "0.3"
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "json"] }

[dev-dependencies]
tempfile = "3"
tokio = { workspace = true, features = ["test-util", "net"] }
axum = "0.8"
