[package]
name = "synchrotron-core"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
synchrotron-types.workspace = true
synchrotron-plugins.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
anyhow.workspace = true
chrono.workspace = true
uuid.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tracing-core = "0.1"
prometheus-client = "0.22"
tokio.workspace = true
rusqlite = { version = "0.34", features = ["bundled"] }

[dev-dependencies]
tempfile = "3"
serde_yaml_ng = "0.10"
