[package]
name = "synchrotron-reconcile"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
synchrotron-types = { workspace = true }
synchrotron-core = { workspace = true }
synchrotron-plugins = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
serde_yaml_ng = "0.10"
tokio = { workspace = true }
