[package]
name = "synchrotron-reconcile"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
synchrotron-types = { workspace = true }
synchrotron-core = { workspace = true }
synchrotron-plugins = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
synchrotron-kube = { workspace = true }
serde_yaml_ng = "0.10"
serde_json = { workspace = true }
tokio = { workspace = true }
tempfile = "3"
rusqlite = { version = "0.34", features = ["bundled"] }
kube = { version = "0.95", default-features = false, features = ["client", "rustls-tls", "runtime"] }
